# Generated by Django 3.1.4 on 2021-01-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('description', models.TextField(default='Sorry, no description available yet. We are working on it :)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(max_length=150)),
                ('img_url', models.URLField(default='https: // bigseventravel.com/wp-content/uploads/2019/10/def.jpg')),
            ],
        ),
    ]
