# Generated by Django 3.1.4 on 2021-01-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_auto_20210105_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FestivalReview',
        ),
    ]
