# Generated by Django 3.1.4 on 2021-01-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_delete_festivalreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='img_url',
            field=models.URLField(default='https: // bigseventravel.com/wp-content/uploads/2019/10/def.jpg'),
        ),
    ]
