# Generated by Django 3.1.4 on 2021-01-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_festival_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='description',
            field=models.TextField(default='Sorry, no description available yet. We are working on it :)'),
        ),
    ]
