# Generated by Django 3.1.4 on 2021-01-06 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0005_festival_description'),
        ('reviews', '0002_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='festivals.festival'),
        ),
    ]
