export const OPEN_SUBMENU = 'OPEN_SUBMENU';
export const CLOSE_SUBMENU = 'CLOSE_SUBMENU';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL';

export const USER_LOADING = "USER_LOADING"; 
export const USER_LOADED = "USER_LOADED"; 
export const AUTH_ERROR = "AUTH_ERROR"; 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"; 
export const LOGIN_FAIL = "LOGIN_FAIL"; 
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const FESTIVALS_LOADING = "FESTIVALS_LOADING";
export const FESTIVALS_LOADED = "FESTIVALS_LOADED";
export const FESTIVALS_LOAD_FAIL = "FESTIVALS_LOAD_FAIL";