export const OPEN_SUBMENU = 'OPEN_SUBMENU';
export const CLOSE_SUBMENU = 'CLOSE_SUBMENU';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL';

export const USER_LOADING = "USER_LOADING"; 
export const USER_LOADED = "USER_LOADED"; 
export const AUTH_ERROR = "AUTH_ERROR"; 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"; 
export const LOGIN_FAIL = "LOGIN_FAIL"; 
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const FESTIVALS_LOADING = "FESTIVALS_LOADING";
export const FESTIVALS_LOADED = "FESTIVALS_LOADED";
export const TOP_FESTIVALS_LOADED = "TOP_FESTIVALS_LOADED";
export const FESTIVALS_LOAD_FAIL = "FESTIVALS_LOAD_FAIL";
export const TOP_FESTIVALS_LOAD_FAIL = "TOP_FESTIVALS_LOAD_FAIL";
export const FESTIVAL_DETAILED_LOADED = "FESTIVAL_DETAILED_LOADED";

export const FESTIVAL_REVIEWS_LOADING = "FESTIVAL_REVIEWS_LOADING"
export const FESTIVAL_REVIEWS_LOADED = "FESTIVAL_REVIEWS_LOADED"
export const CREATE_REVIEW = "CREATE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";

export const ADD_LIKE = "ADD_LIKE"
export const ADD_DISLIKE = "ADD_DISLIKE"
export const LIKES_LOADED = "LIKES_LOADED"
export const DISLIKES_LOADED = "DISLIKES_LOADED"
export const USER_ALREADY_LIKED = "USER_ALREADY_LIKED"